services:
  - type: web
    name: attendance-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: main.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-super-secret-key-123
      - key: MAIL_USERNAME
        value: bishalgogoi09735@gmail.com
      - key: MAIL_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromService:
          type: mysql
          name: attendance-db
          property: connectionString

  - type: mysql
    name: attendance-db
    ipAllowList: []
    plan: free
    version: "8.0.23"
